import = ["~/.config/alacritty/rose_pine.toml"]

[shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux attach || tmux"]

[colors.primary]
background = "#080808"
foreground = "#F0F0F0"

[font]
size = 13.0

[window]
opacity = 0.93
