vim.cmd.colorscheme('gruvbuddy')
-- vim.api.nvim_command('hi StatusLineNC guibg=NONE guifg=#ffffff gui=NONE')
-- vim.api.nvim_command('hi StatusLine guibg=NONE guifg=#ffffff gui=NONE')
-- vim.api.nvim_command('hi StatusLineTerm guibg=NONE guifg=#ffffff')
vim.api.nvim_command('hi LineNr guibg=NONE guifg=#827d7d')
-- vim.api.nvim_command('hi SignColumn guibg=NONE')
vim.api.nvim_command('hi EndofBuffer guibg=NONE guifg=#000000 gui=NONE')
-- vim.api.nvim_command('hi Normal guibg=NONE')
-- vim.api.nvim_command('hi VertSplit guibg=NONE guifg=NONE')
